name: 'ai-spam-guard'
description:
  'Scan new issues and comments with GitHub Models AI prompts; label or hide
  spam automatically.'
author: 'GitHub'
branding:
  icon: 'shield'
  color: 'purple'

inputs:
  token:
    description:
      'GitHub token with `issues`, `pull-requests`, and `models: read`
      permissions'
    required: false
    default: ${{ github.token }}
  spam-label:
    description: 'Label to add when generic spam is detected'
    required: false
    default: 'spam'
  ai-label:
    description: 'Label to add when AI-generated content is detected'
    required: false
    default: 'ai-generated'

runs:
  using: 'node16'
  main: 'dist/index.js'
